name: CMake Windows Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Cache vcpkg dependencies
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: C:/vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-


    # Step 3: Install dependencies (only if not cached)
    - name: Install Dependencies
      run: |
        choco install cmake ninja visualstudio2019buildtools
        if (!(Test-Path "C:/vcpkg")) {
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat
        }
        echo "C:/vcpkg" >> $env:GITHUB_PATH

    # Step 4: Generate build files
    - name: Configure
      run: |
        cmake -B build
        
    # Step 5: Build the project
    - name: Build
      run: |
        cmake --build build --config Release
